services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper_playground
    ports:
      - "2181:2181"
    volumes:
      - C:\kafka\zookeeper_playground\data:/var/lib/zookeeper_playground
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_playground
    ports:
      - "29092:9092"
    volumes:
      - C:\kafka\data:/var/lib/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_playground:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
    depends_on:
      - "zookeeper"
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
